### ISSUE TITLE
atsign.ged does not appear to be legal GEDCOM

### ISSUE THREAD

**Issue by dthaler** [gedcom7code/test-files#2]
atsign.ged (both the 5 and 7 versions) have no @xref_id@ between the level and tag for "0 NOTE" / "0 SNOTE".  In the gedcom specs, 0 is stated to mean it must be a record and the NOTE/SNOTE record structures are speced as requiring an xref id.   The point of the test is presumably not to test that part, but rather the payloads, so the files should be updated to add xref ids to all records.

**Comment by tychonievich** [comment]
Per the 7.0 spec, section 1.3

> Each record to which other structures point must have a cross-reference identifier. A record to which no structures point may have a cross-reference identifier, but does not need to have one

The 5.5.1 spec is ambiguous on whether non-identified records are allowed.

Thus, the 7.0 file was valid without these identifiers, the 5.5.1 file might have been too, but I've still merged these PRs because, as noted in the issue, including identifiers for no-target records is more common and testing their presence wasn't the goal of these files..

**Comment by dthaler** [comment]
> Per the 7.0 spec, section 1.3
> 
> > Each record to which other structures point must have a cross-reference identifier. A record to which no structures point may have a cross-reference identifier, but does not need to have one
> 
> The 5.5.1 spec is ambiguous on whether non-identified records are allowed.
> 
> Thus, the 7.0 file was valid without these identifiers, the 5.5.1 file might have been too, but I've still merged these PRs because, as noted in the issue, including identifiers for no-target records is more common and testing their presence wasn't the goal of these files..

Hmm, I had missed that quoted text.  But that means the GEDCOM 7 spec has a contradiction.

The spec has lines like this for each record:
```gedstruct
n @XREF:INDI@ INDI                         {1:1}  g7:record-INDI     
```

Where the cross-reference identifier is not denoted as optional.  To be consistent with the paragraph quoted, it would need to be 
```gedstruct
n [@XREF:INDI@|<NULL>] INDI                         {1:1}  g7:record-INDI     
```

**Comment by dthaler** [comment]
Filed https://github.com/FamilySearch/GEDCOM/issues/408
